
// Check some assertions
#ifndef CONFIG_64BIT
#error Compiles only on 64-bit
#endif

#ifndef CONFIG_X86_64
#error CONFIG_X86_64
#endif

enum {
  MINUTEMAN_ATTR_UNSPEC,
  MINUTEMAN_ATTR_VIP_IP,
  MINUTEMAN_ATTR_VIP_PORT,
  MINUTEMAN_ATTR_BE_IP,
  MINUTEMAN_ATTR_BE_PORT,
  MINUTEMAN_ATTR_BE_AVAIL,
  __MINUTEMAN_ATTR_MAX,
};

#define MINUTEMAN_ATTR_MAX (__MINUTEMAN_ATTR_MAX - 1)

enum {
  MINUTEMAN_CMD_UNSPEC,
  MINUTEMAN_CMD_NOOP,
  MINUTEMAN_CMD_ADD_VIP,
  MINUTEMAN_CMD_DEL_VIP,
  MINUTEMAN_CMD_ADD_BE,
  MINUTEMAN_CMD_DEL_BE,
  MINUTEMAN_CMD_SET_BE,
  MINUTEMAN_CMD_ATTACH_BE,
  MINUTEMAN_CMD_DETACH_BE,
  __MINUTEMAN_CMD_MAX,
};

#define MINUTEMAN_CMD_MAX (__MINUTEMAN_CMD_MAX - 1)

static struct nla_policy minuteman_policy[MINUTEMAN_ATTR_MAX + 1] = {
  [MINUTEMAN_ATTR_VIP_IP] = {
    .type = NLA_U32,
  },
  [MINUTEMAN_ATTR_VIP_PORT] = {
    .type = NLA_U16,
  },
  [MINUTEMAN_ATTR_BE_IP] = {
    .type = NLA_U32,
  },
  [MINUTEMAN_ATTR_BE_PORT] = {
    .type = NLA_U16,
  },
  [MINUTEMAN_ATTR_BE_AVAIL] = {
    .type = NLA_U8,
  },
};

